//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timer_LKS_Hotel_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDCheckOut
    {
        public int ID { get; set; }
        public int ReservationRoomID { get; set; }
        public int FDID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual ReservationRoom ReservationRoom { get; set; }
        public virtual FoodsAndDrink FoodsAndDrink { get; set; }
    }
}
